### ISSUE TITLE
Reading calibrated data always selects the same device

### ISSUE THREAD

**Issue by tdbenson** [sparkfun/SparkFun_AS7265x_Arduino_Library#1]
The calibrated results functions all duplicate the first devices data. 

In other words, `getCalibratedA` returns the same value as `getCalibratedG` because there is no call to `selectDevice` in the `getCalibratedValue` function.

I'm assuming `getCalibratedValue` should be more like the `getChannel` where it accepts the proper device as an argument.

**Comment by nseidle** [comment]
Yep! Good catch. getCalibratedValue() now calls appropriate device. I've rolled the library version. Please install v1.0.1 and let me know if you have any more issues.

**Comment by Michael-Raven** [comment]
The effect of this bug is very evident in the sample data, and graphs, in the Hookup Guide
