### ISSUE TITLE
Bug in enableIndicator, disableIndicator, and setIndicatorCurrent.

### ISSUE THREAD

**Issue by kchinzei** [sparkfun/SparkFun_AS7265x_Arduino_Library#11]
This is related to the closed issue #2, but there is one more bug to fix.

This bug incorrectly turns on/off the white bulb under certain sequence of turn on/off of the indicator and IR/UV bulbs.
You can reproduce it by Bulb_Test.ino code in my pull request #10 . I tested on Arduino nano and ESP8266.

The bug was around selectDevice(AS72651_NIR) - it should be called BEFORE virtualReadRegister(AS7265X_LED_CONFIG), because every AS7265x sensor has own AS7265X_LED_CONFIG register.

**Comment by nseidle** [comment]
Thanks! Fixed in latest commit.
