### ISSUE TITLE
so much difference in the output data

### ISSUE THREAD

**Issue by yashmewada9618** [sparkfun/SparkFun_AS7265x_Arduino_Library#12]
I am currently working on this sensor along with esp32 and Bluetooth functionality. The sensor works fine. My basic application is I read the data while medicine as a sample. I take 50 samples at a time and send that the average of those 50 data via Bluetooth.
When I compare it with the next new sample, there is a difference of more than 5% with the same batch of samples whereas it should be less than 3% according to the manufacturer.
I tried many ways in measuring the data. Even edited the library to measure all three bulbs individually not simultaneously but the difference in data remains the same.
Can anyone help me with this issue or tell me what am I doing wrong here.
![image](https://user-images.githubusercontent.com/54842967/119253343-770e1200-bbce-11eb-9196-005ffbb9460f.png)
here is the way I take measurements.
Note:I have edited the library and added arg to takemeasurementswithbulb function

Thanks and regards
Y

**Comment by nseidle** [comment]
We can only help with the library and not the functionality or performance of the sensor. Sorry but this is a question for AMS.
