### ISSUE TITLE
AS7265X::get'X' Function being slow.

### ISSUE THREAD

**Issue by cmosthings** [sparkfun/SparkFun_AS7265x_Arduino_Library#18]
I am using the Triad Spectroscopy Sensor - AS7265x via I2C with a Thing Plus - ESP32 WROOM (USB-C).
As a code base I used the MaxReadRate Example. 
The Problem I have been trying to figure out is why my sensor only transmitts about 3Hz and I belive that i comes down to the
AS7265X::virtualReadRegister(uint8_t virtualAddr) function needing a very long time to actually get the data from the Sensor. 
Is there any reasonable way to Improve this behaviour? I have checked against the spec sheet and it is exactly the behaviour outlined in it.  I would like to get a maximum read rate over about 10 individual measurements and this is just a block. 
Would Serial be faster?

**Comment by cmosthings** [comment]
To answear my own question Serial is factor 2X faster. Still nowhere near the theoretically possible 180Hz.
I tuned the Speed over I2C to about 10Hz with Raw Values and Over Serial I got 20Hz just out of the box.

The key to get the I2C to be faster is tho reduce the delay(AS7265X_POLLING_DELAY); to a shorter Period 1ms should be already better. I reduced it to 100millis for myself instead of the 5ms and it worked great.

**Comment by nseidle** [comment]
Did you adjust the integration time? By default, the integration time is 0x20 or 32*1.2.78ms = 88.96ms. This matches your 10Hz I2C experience. Consider decreasing setIntegrationCycles() to achieve the integration time you desire. 

![image](https://github.com/sparkfun/SparkFun_AS7265x_Arduino_Library/assets/117102/074b5bcd-8adb-4a1e-a28a-c77c87604ab3)

Datasheet page [label 32](https://ams.com/documents/20143/36005/AS7265x_DS000612_1-00.pdf/08051c8a-a7f6-6231-7993-2d3fe0bf38b8).

**Comment by cmosthings** [comment]
Yes I did setIntegrationCycles(1) and the Hz is still stuck at what I mentioned before. I Measured the time between resetting the MeasurementMode(AS7265X_MEASUREMENT_MODE_6CHAN_ONE_SHOT) and dataAvailable to approximately 2*2.78ms which is great and as expected. Getting the data from the sensor over I2C seems to be the major bottleneck limiting to cycle times of approximately 100ms this is the issue I and others are having.
