### ISSUE TITLE
Is there a way to improve the sampling rate?

### ISSUE THREAD

**Issue by justinmcgrath** [sparkfun/SparkFun_AS7265x_Arduino_Library#7]
When using this, I get a sampling rate of about 5 Hz. I don't know if this is a limitation of the chip, or if it has to do with this library. I couldn't find the information in the spec sheet. Has anyone here achieved higher rates, or do you have some information about it?

For what I'm doing, 40 Hz would be a good rate.

**Comment by nseidle** [comment]
Have you checked out [Example 5](https://github.com/sparkfun/SparkFun_AS7265x_Arduino_Library/blob/master/examples/Example5_MaxReadRate/Example5_MaxReadRate.ino)? It will demonstrate how to increase the sampling rate.
