### ISSUE TITLE
Not getting the right output

### ISSUE THREAD

**Issue by d-e-e-p-i-k-a** [sparkfun/SparkFun_AS7265x_Arduino_Library#9]
I am trying to interface AS7265X with arduino uno,  I have used a level shifter to vary the voltage for the SCL and SDL pins. The triad sensor is powered ON. But while i am trying to read the data, it says -"Sensor does not appear to be connected. Please check wiring. Freezing..."

**Comment by JarrettR** [comment]
A level shifter doesn't really make sense in the context of I2C. I'd suspect that you're trying to do something with push-pull outputs, not realising that I2C is only open drain.

**Comment by nseidle** [comment]
I've added a few tweaks to the isConnected() function (device requires ~650ms of startup time). Please give it a try and open new issue if it persists.
